# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f45fd44c23cb32b4aba6eb72343d885aea74b109001bb2092b4edb15b46b314b9c54ddb1194892fde8e07cc6af938f5febb3411d6144e2f7003f112b6bf295f3

test:
  secret_key_base: a76eb3ad17941903abdcaa5f01b1275221b015987994b33569655fc793b6cb8dbfeed41c004c4606de3c03af980454b20293868c3a97873d3bfad4d0627247f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
